### ISSUE TITLE
option for setting height and top of a region

### ISSUE THREAD

**Issue by shuvangkardas** [wavesurfer-js/wavesurfer.js#1259]
Hey Katspaugh, Thanks for such amazing library. I am using region plugin. I want variable and variable top region. There is no option for setting height and top of a region. Please help me find a solution

**Comment by ArTiSTiX** [comment]
@shuvangkar Do you have usecase examples that could be also be useful to other users ?
Are you using wavesurfer v2 ?
I don't plan to make improvements to v1 so this could be necessary to upgrade to v2 if your request is implemented.

As far as i know, you can "select" a region dom elements through its data-id attribute (using javascript, or css `region[data-id=XXX]`, and override top and height properties with !important).

I also struggled with inline styling, it seems to be a choice for wavesurfer (no css), but as an improvement, we could implement an style option passed to regions to set some inline style property set on init instead of default `{height: '100%', top: 0, zIndex: 2}` that could do the trick.
