### ISSUE TITLE
Show waveform of a big audio file as it loads

### ISSUE THREAD

**Issue by ErezDalet** [wavesurfer-js/wavesurfer.js#1390]
Hi,
I want to show the waveform of a big audio file (at least 100 MB, at least 1 hour).
I can't wait for the whole file to load because it takes a lot of time.
I need to show it right from the start, as it loads.

I know that I can somehow use array of "Pre-recoded Peaks", but it is heavy to receive this data from my server, so I actually can receive arrays of "Pre-recoded Peaks" in chunks, meaning every 1 second I get 10 minutes of the audio as "Pre-recoded Peaks".
But I didn't see a way to concatenate the arrays and update my existing waveform.

Is there a way I can show the waveform as it loads?
(using chunks of "Pre-recoded Peaks" or any other way?)
Thanks!

**Comment by thijstriemstra** [comment]
Try the `backend: 'MediaElement' option.

**Comment by ErezDalet** [comment]
Thanks but this options just allows to hear the audio before the full waveform loads.
It doesn't display it until it is fully loaded.

**Comment by GitHubRakeshSharma** [comment]
You might need to write your own drawer class. It just needs some minor modifications.

**Comment by ErezDalet** [comment]
@GitHubRakeshSharma What do you mean? Do you have an example?

**Comment by GitHubRakeshSharma** [comment]
I am sorry, I am a little short on time. But: e.g. take the multicanvas drawer and get yourself through the whole structure. You will find that the drawing takes multiple steps and finalizes with the drawLineToContext. There are many point where you can modify the methods to for example store the last drawn point [(x|y)-value] and then just let the drawer draw the next chunk from that starting point.

**Comment by awenger63** [comment]
Hi, 
If i understand your need, for me the best way it's use pre-recoded peaks like you suggest, but you need to have one or more json file with peaks data to do this.
if you want to load 10 minutes by 10, you always need to concat it with array contain [0,0, ... 0,0] to replace the part of peaks not arrived, because your wave must contain data for all file duration.

I have a little solution I have tested, it's to update peaks data by other way and redraw (without change code like suggest @GitHubRakeshSharma ) perhaps you can adapt and use this code :

`function drawnWaveJson(peaks) {
                    wavesurfer.backend.setPeaks(peaks,wavesurfer.getDuration());
                    if (wavesurfer.peakCache !== null) {
                        wavesurfer.peakCache.clearPeakCache();
                    }
                    wavesurfer.drawBuffer();
                }`
you can call it fisrt whit partial peaks completed by 0 when wavesurfer is  'ready' and update each time you recevied more peaks from your server.

see also this code 

`let ajax = WaveSurfer.util.ajax({
                    url: 'http://yourserverurl/file.json',
                    responseType: 'json'
                });`

you can directly get data or partial data from your serveur !
Only need : have one or more json file (see audiowaveform using. you can find a lot of information on other issues talk about json/peaks )

Hope this can help you.

**Comment by shriyajuneja** [comment]
Hey, Any update on this issue ? stuck on same issue

**Comment by marizuccara** [comment]
Hi, you can try something like this:
```
wavesurfer.util
    .ajax({
          responseType: 'json',
           url: './src/configurations/b.json'
      })
       .on('success', (peaks) => {
             const b = wavesurfer.backend.getPeaks();
             wavesurfer.backend.setPeaks(
                              b.concat(peaks.data), 
                              wavesurfer.backend.getDuration() + peaks.duration
             );
             if(wavesurfer.isPlaying()) wavesurfer.play(wavesurfer.currentTime);
             if (wavesurfer.peakCache !== null) { 
                   wavesurfer.peakCache.clearPeakCache();
                   wavesurfer.drawBuffer();
                   wavesurfer.drawer.progress(wavesurfer.backend.getPlayedPercents());
               }
 });
```
But pay attention, if you update your data too often, the concat operation can be too expensive.
