### ISSUE TITLE
setPlaybackRate distorted with WebAudio backend

### ISSUE THREAD

**Issue by yxwei0129** [wavesurfer-js/wavesurfer.js#1524]
this.wavesurfer.setPlaybackRate(2.0)

**Comment by aivo0** [comment]
The correct issue descriptions should be "Method setPlaybackRate leads to sound distortion with WebAudio backend".

This is because this happens when wavesurfer backend is WebAudio and not when MediaElement. I was playing a regular 3-minute MP3 file. Using latest Chrome (v 73) and Firefox (66), Windows 10. 

WebAudio is the default backend. I also sadly need to use it for 2 reasons: 
1. With MediaElement the browser essentially downloads the audio file twice (unless I supply peaks array) - one is streamed for user playback, the other is for Wavesurfer to generate peaks to show the waveform. I mostly serve user uploaded files on my website so I can't use the wavesurfer.js to generate the peaks beforehand. I know that it's possible to generate peaks on the server as well but it's currently more trouble than it's worth. 
2. When I exported peaks using the exportPCM method and used MediaElement backend, the audio and peaks were slightly off :(

But it would be great to have setPlaybackRate work with Webaudio backend as well.

And by the way another bad part of backend WebAudio is that browsers don't cache the file :( And the file needs to be fully downloaded before playback unless using those peaks, which don't work correctly for me anyways. So it seems like a bad default.
