### ISSUE TITLE
splitChannels Argument Only Partially Supports 3-Channel Audio

### ISSUE THREAD

**Issue by dan24678** [wavesurfer-js/wavesurfer.js#1906]
### Wavesurfer.js version(s):
3.3.1

### Browser and operating system version(s):
Chrome on Mac

### Code needed to reproduce the issue:
Construct a Wavesurfer instance with the "splitChannels: true" argument in which you load audio that contains 3 channels. Here is a sample wav file:

[26394717-ddfe-4924-8505-9cd5f77cddc3_multichannel.wav.zip](https://github.com/katspaugh/wavesurfer.js/files/4451332/26394717-ddfe-4924-8505-9cd5f77cddc3_multichannel.wav.zip)

### Use behaviour needed to reproduce the issue:
All 3 channels are rendered correctly in the drawn waveform. That part works great.

When you play it back, however, behavior is as follows:

Channel 1: Plays through left speaker
Channel 2: Plays through right speaker
Channel 3: No audio can be heard in a standard stereo speaker setup

I'm not sure if there are implications for surround sound with this and in the current implementation maybe I would need more physical speakers to match the number of channels? But for my application it would be fantastic if either by default, or via an additional argument, I could have the audio from Channel 3 be sent through either the left or right speaker. Thanks.

**Comment by thijstriemstra** [comment]
@DrLongGhost I think the issue might be related to the default AudioContext settings wavesurfer.js uses. Basically instantiates this AudioContext for you, if you don't supply one yourself:

```javascript
new OfflineAudioContext(1, 2, 44100);
```

where 1 is nr of channels. Also see #1865 where higher samplerates were not rendered properly.

If you pass your own AudioContext (with 2/3 channels) it should probably work, can you give that a try?

**Comment by thijstriemstra** [comment]
> If you pass your own AudioContext (with 2/3 channels) it should probably work, can you give that a try?

And if it doesn't, adjust the hardcoded nr (`1`) of channels here: https://github.com/katspaugh/wavesurfer.js/blob/576c0afa317a44e37257389166b3c86a500aaddf/src/webaudio.js#L92

**Comment by DrLongGhost** [comment]
@thijstriemstra -- Thanks for the response. It occurs to me now that there are actually three possible ways forward here. I'll start with the one I intend to use for now.

OPTION A: Use MediaElement

It looks like using the MediaElement backend supports playing back 3 channel audio when only 2 speakers are present. Since this is good to go, I'll probably use this as the workaround unless one of the other options can be made to work.

OPTION B: Make Playback work with AudioContext

I tried both of @thijstriemstra's suggestions above but neither altered the behavior that I was seeing. It looked like I'm only allowed to make a new AudioContext in response to a user click or gesture so I wasn't sure how to pass that into the config when instantiating wavesurfer since there would not have been a click event at that point.

Instead, I set up code that would run the following when the user clicks the Play button:

window.WaveSurferOfflineAudioContext = new (window.OfflineAudioContext ||
                window.webkitOfflineAudioContext)(3, 2, sampleRate);

I also just tried hard-coding the "3" in the library code per the second suggestion.

In all cases, the behavior is unchanged from the original bug report -- Channels 1 and 2 playback left and right, and Channel 3 is muted.

I found [this page](https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/channelInterpretation) which describes downmixing/merging channels but I'm not sure how I'd go about doing that or if it's even necessary. It seems like the changes I tried should work but they didn't.

OPTION C: Using a different playback file

Is it possible to have Wavesurfer read in a URL of a 3-channel audio file to use when rendering the visual and overlaying regions while accepting a different URL to a 2-channel audio file to use when triggering playback?

If this is cleanly supported in Wavesurfer, it might be a better workaround than OPTION A since I know that MediaElement was deprecated because it's flaky at times.

**Comment by thijstriemstra** [comment]
>  I wasn't sure how to pass that into the config when instantiating wavesurfer since there would not have been a click event at that point.

Something like:

```html
<button onclick="createWS()">Create</button>
<script>
function createWS() {
    var ws = WaveSurfer.create(options_inc_custom_audio_context);
    // etc
}
<script>
```

**Comment by DrLongGhost** [comment]
I had earlier tried to fix this with the workarounds that @thijstriemstra suggested and didn't have much success, so I ended up sticking with the MediaElement to fix the problem that way.

 But this issue came up again for me recently with videojs-wavesurfer where the use of MediaElement might make it harder to update the code to pull in a waveform from a source other than the parent video. Per [this ticket](https://github.com/collab-project/videojs-wavesurfer/issues/117)
