### ISSUE TITLE
Safari doesnt work with your playlist example. Any work around? I am kinda novice and would love the code.

### ISSUE THREAD

**Issue by daviszoo** [wavesurfer-js/wavesurfer.js#1965]
It seems you have to click pause twice to play it after clicking the link of a song. You can test it on your actual playlist example. That is the code I am using if you coiuld just update that page.

**Comment by pcfields** [comment]
I am experiencing the same issue. Does anyone know how to resolve this?

**Comment by sundayz** [comment]
Hi guys, this is likely because the browser is blocking autoplay audio. Chrome does this too, if you open your browser console (CTRL+SHIFT+I in Chrome) you will see warnings in the console telling you the audio is blocked because the user has not interacted with the page.

Since clicking a link is technically "user interaction" you might want to try manually calling wavesurfer.play() inside of the event listener which handles playlist clicking, instead of relying on autoplay.

**Comment by pcfields** [comment]
@daviszoo I was able to resolve this issue by creating an AudioContext and then passing it to wavesurfer options. In my button event handler I then call audioContext.resume() which allows the audio to play
