### ISSUE TITLE
Performance for long audio files

### ISSUE THREAD

**Issue by msjaber** [wavesurfer-js/wavesurfer.js#2055]
Hey,

I was experimenting with Wavesrufer for long audio files (more than 60m), and I noticed that the average generated wave is around 300,000px wide. Those pixels are divided into 75 canvas, each of 4000px.

![Screen Shot 2020-08-24 at 4 52 44 PM](https://user-images.githubusercontent.com/1570921/91633989-75277180-e9f5-11ea-98e9-6f0fca2faaa7.png)

This was very heavy for the browser to handle the computation (especially when zooming in and out). 

I was wondering if this the right behavior for long audio files or am I doing something wrong?

Note that, other experiments with [bbc/peaks.js](https://github.com/bbc/peaks.js), I found they reuse the same 2000px wide canvas and only generate the required wave portion, and the performance was excellent.

Thanks

**Comment by sundayz** [comment]
#1622 would fix this problem. Chrome also has a new css property that lets you tell the browser when things should not be rendered, but I dont know if it works on canvas elements, and it's only available in chrome right now: https://web.dev/content-visibility/

I don't know enough about the wavesurfer renderer to say why the same canvas isn't reused. You can also create your own waveform renderer and give it to wavesurfer to use instead of the default renderer, if you want to make a more efficient one (for example using one canvas, or using webgl, etc)

**Comment by thijstriemstra** [comment]
> I don't know enough about the wavesurfer renderer to say why the same canvas isn't reused. 

I think one of the reasons was a dimensions limitation of a canvas element. But not sure if browsers fixed this yet and if it's still something wavesurfer needs to workaround. wavesurfer.js is a collection of a lot of ideas, workarounds and implementations by many people and sometimes these ideas clash and are incompatible, or even obsolete.
