### ISSUE TITLE
Region plugin: Moving region on mobile also scrolls the waveform

### ISSUE THREAD

**Issue by sundayz** [wavesurfer-js/wavesurfer.js#2080]
### Wavesurfer.js version(s):
4.x

### Use behaviour needed to reproduce the issue:
scrollParent has to be "true" on the WaveSurfer instance.

On small screens when using scroll on the wavesurfer container, trying to drag a region now also scrolls the container. In 3.3.3, moving the region works fine.

### Workaround

```js
wavesurfer.container.addEventListener('touchmove', e => {
    if (e.target === region.element) {
        e.preventDefault();
    }
});
```

Where "region" in the code example is the region which you want to be able to drag. Calling preventDefault here stops the container from scrolling when a touchmove event comes from the region. You may also have to do this for mousemove if you use scrollParent on desktop.

### Possible fix?

Call event.stopPropagation() in region onMove? Not sure if this will break anything.

**Comment by thijstriemstra** [comment]
> Call event.stopPropagation() in region onMove? Not sure if this will break anything.

thoughts @marizuccara?

**Comment by marizuccara** [comment]
Calling event.stopPropagation() in region onMove seems to break anything on desktop. But trying on devtools mobile toolbar the problem described by @sundayz seems persist. Now I don't know if device devtool is really reliable, because I usually dev on Desktop.. 
I noted also one thing. Commenting, in the onMove, this statement, the problem on mobile seems solved. 
```
  if (e.targetTouches && e.targetTouches[0].identifier !== touchId) {
       return;
 }
```
But I don't know if commenting this statement has any implications..

**Comment by sundayz** [comment]
Maybe devtools uses `mousemove` instead of `touchmove`, i did not check. I guess this fix needs to be applied to both events
