### ISSUE TITLE
Always start playing from 0 seconds, cannot play the specified position , when click wavesurfer

### ISSUE THREAD

**Issue by zhangzygit** [wavesurfer-js/wavesurfer.js#2103]
### Wavesurfer.js version(s):
4.2.0

### Browser and operating system version(s):
Chrome  86.0.4240.183
MacOS 10.15.7
### Code needed to reproduce the issue:

the size of  the audio files is 98m

![Nov-09-2020 18-58-01](https://user-images.githubusercontent.com/32352808/98533185-9b06a780-22bd-11eb-90cb-62c25ab19707.gif)

**Comment by marizuccara** [comment]
Hi! Can you reproduce your problem with an example, maybe with codesandbox?

**Comment by taskaijo** [comment]
if the backend parameter not 'WebAudio' it does not work

**Comment by entonbiba** [comment]
@zhangzygit can you provide a link to the audio file in question for testing?

**Comment by HYiteam** [comment]
backend: 'WebAudio'

**Comment by andrewsml** [comment]
@thijstriemstra , have you eventually solved the issue? what the cause was?

**Comment by samuliedvin** [comment]
I believe the problem is how HTMLMediaElement behaves while setting its internal `currentTime` when the server serving audio files is not configured properly. Changing `currentTime` creates a byte range request for the server asking for a part of the audio file - and if this fails, the player sets `currentTime` to 0 by default.

I struggled for a while with this since I had to keep audio files only available for logged in users which meant I had to serve the files with my own implementation. IIRC when I correctly handled the byte range requests Wavesurfer also began to work.

[See this StackOverflow answer for reference.](https://stackoverflow.com/questions/9563887/setting-html5-audio-position)
