### ISSUE TITLE
Draw Waveform without MediaElement

### ISSUE THREAD

**Issue by mozzak** [wavesurfer-js/wavesurfer.js#2233]
Here is the issue I am dealing with:

I have about 10 large wave files on one page. I use prerendered waveforms and have regions as well.

If I use backend='MediaElement' it loads one waveform after the other with some lack time. It takes about 20 seconds to get all 10 wave files properly drawn and the ready event fired which I use to render the regions. It just doesn't feel fast enough.

I would like to improve the waveform rendering so I removed the backend='MediaElement'. Rendering of the 10 waveforms is now almost instant. That part is great. However, the 'ready' event never fires which is used to render the regions. Once I click inside the waveform that is the time it fires the 'ready' event and the region will be drawn.

Ideal solution: I don't use the backend='MediaElement' to get the speedy waveform rendering but somehow programmatically set each wavesurfer into ready stage instead of having to click in it so the regions can be drawn as well.

Is there a way to trigger what the click on waveform is doing? Or is there any other way of doing this? Thoughts?

**Comment by mozzak** [comment]
found a workaround: calling seekTo(0) does the trick.

Still wondering if there is a better solution though.

**Comment by entonbiba** [comment]
The ready event runs once the audio and waveform is drawn on the waveform instance. Do you have sample code to look at where it is not running?

**Comment by MrdUkk** [comment]
i got this problem too. but with single waveform. i need *only* waveform visualization with timeline. without backend and <audio/> html5 tag. the problem is very easy to spot: 
1. create timeline plugin with defaults in wavesurfer.init()
2. define non-valid URL for wavesurfer.load() . (so endpoint is never reached).
3. pre-define peaks array (1second is enough)
4. pre-set duration (=1sec) to wavesurfer.load function. and start browser.
5. you will see waveform properly drawed.
5. but without *first* mouse click no timeline is even drawed! (because 'ready' event is NOT fired).

P.S.
...and as i see - wavesurfer plugins will suffer simular bug with backend=MediaElement. Thats because 'waveform-ready' event will be fired instead of 'ready' that plugins (elan,markers,regions,timeline,minimap,spectrogram) is waiting for.
