### ISSUE TITLE
Zoom performance

### ISSUE THREAD

**Issue by mikevercoelen** [wavesurfer-js/wavesurfer.js#2239]
The performance of zooming in is really bad, is there any stuff I could do to optimise it?

**Comment by thijstriemstra** [comment]
See #1622 for an attempt to improve zooming performance. Could use some work.

**Comment by entonbiba** [comment]
@mikevercoelen how big is the audio file that you are loading?

I added a debounce feature long time ago for the resize wave part of the code, I think that will help improve the zoom performance if we add it there as well.

https://github.com/katspaugh/wavesurfer.js/blob/2e49044b53680cdd30ec83e65d4fd49b36075e1d/src/wavesurfer.js#L491

**Comment by Mladja** [comment]
First of all, thank you for this library @thijstriemstra. I managed to do a lot of good things. 
The problem I have at the moment is when I try to zoom in on a very large/long file and I see that other people have these problems as well.
Also, the problem is the same with the timeline plugin.

I think a good part of the performance problem is because position => left is used to move the canvas.
This approach is also used on the Timeline plugin.

[Pefrormance post](https://developer.mozilla.org/en-US/docs/Web/Performance/Fundamentals)
[Performance just shorter](https://www.sitepoint.com/atoz-css-translate-vs-position/)

If you were to move Canvas elements via transform instead of left property, do you see any problems with that?
How cursor plugin will behave, seek, and so on...? 

I would love to try tomorrow and do PR if I succeed.

![Screenshot 2021-11-26 at 12 11 16](https://user-images.githubusercontent.com/7488636/143572212-66b8cae2-5705-454e-8ce8-0e859d8bd2eb.png)

**Comment by thijstriemstra** [comment]
try a pr, so we can take a look
