### ISSUE TITLE
Record and show the waveform on-time

### ISSUE THREAD

**Issue by vul9156** [wavesurfer-js/wavesurfer.js#272]
i have seen the "Showing microphonwhich  recording wav in realtime? #263", i find out that there are 1. drawBuffer and 2. drawAsItPlays two function , would you please tell me that which is better for microphone?(because record is save into a bufffer)
and please tell me how to use these two function for example!
because when i load the url and the wavesurfer show up, then when should i use function "drawAsItPlay"?
thank you a lot.

**Comment by thijstriemstra** [comment]
Looks like `drawAsItPlay` was removed at some point. The microphone plugin uses the `wavesurfer.loadDecodedBuffer` method to redraw the waveform every time the `audioprocess` event is called:

```javascript
/**
 * Redraw the waveform.
 */
reloadBuffer: function(event) {
    if (!this.paused) {
        this.wavesurfer.loadDecodedBuffer(event.inputBuffer);
    }
},
```
`wavesurfer.loadDecodedBuffer` clears the existing waveform, loads and draws the latest audio buffer from the microphone. In order to render a contineous stream you'd want to keep the previous buffer and append the new buffer. As a proof of concept I tried adding a `appendBuffer` method to `wavesurfer`:

```javascript
/**
* Appends two ArrayBuffers into a new one.
* 
* @param {ArrayBuffer} buffer1 The first buffer.
* @param {ArrayBuffer} buffer2 The second buffer.
*/
appendBuffer: function(buffer1, buffer2) {
    var numberOfChannels = Math.min( buffer1.numberOfChannels, buffer2.numberOfChannels );
    var tmp = this.backend.ac.createBuffer( numberOfChannels, (buffer1.length + buffer2.length), buffer1.sampleRate );
    for (var i=0; i<numberOfChannels; i++) {
      var channel = tmp.getChannelData(i);
      channel.set( buffer1.getChannelData(i), 0);
      channel.set( buffer2.getChannelData(i), buffer1.length);
    }
    return tmp;
},
```

And changed `microphone.reloadBuffer` to use a new `wavesurfer.appendDecodedBuffer`:

```javascript
appendDecodedBuffer: function (buffer) {
    this.empty();
    if (this.backend.buffer) {
        buffer = this.appendBuffer(this.backend.buffer, buffer);
    }
    this.backend.load(buffer);
    this.drawBuffer();
    this.fireEvent('ready');
},

**Comment by thijstriemstra** [comment]
Storing the results in an array has about the same performance because the whole waveform gets redrawn, so the longer the waveform, the harder the redraw becomes.

```javascript
        function Float32Concat(first, second)
        {
            var firstLength = first.length,
                result = new Float32Array(firstLength + second.length);

            result.set(first);
            result.set(second, firstLength);

            return result;
        }

        var peaks = this.backend.getPeaks(width);
        if (this.savedData === undefined) {
            this.savedData = peaks;
        } else {
            this.savedData = Float32Concat(this.savedData, peaks);
        }

        this.drawer.drawPeaks(this.savedData, width);
        this.fireEvent('redraw', this.savedData, width);
}
```
Need a way to append to the canvas without clearing it every time.

**Comment by katspaugh** [comment]
Thijs, for performance's sake, it would be bettor to draw on the same canvas to the right from the existing drawing. However, you'd need to determine the canvas size beforehand, because if you change it, canvas clears itself.

Or if we could implement scrolling as panning (the same as BBC guys do), the size of the canvas would stay the same and you'd have to redraw it every time anyway. Although with a small fixed canvas it would be quite fast.

**Comment by thijstriemstra** [comment]
Thanks for your feedback. While searching about something like canvas caching I found this interesting statement:

"EaselJS lets you lay out your UI in a hierarchical structure of DisplayObject instances. An instance of Stage is the root for all DisplayObjects and draws everything onto the canvas when you call Stage.update(). Obviously the more elements you have, the longer this operation takes. *EaselJS provides a way to cache your objects using the DisplayObject.cache() method. This draws the object onto a separate off-screen canvas and uses to drawImage() to copy pixels from the cache canvas onto the real one when you call update(), so the next time you call update(), you’re drawing 1 object instead of the 1722 objects that are its descendants.*"

I wonder how they're caching that, I'm from Actionscript world but not sure how `canvas` handles that but it sounds like a possible solution.

**Comment by katspaugh** [comment]
They must be exporting the canvas contents into data URI. Look up `canvas.toDataURI`.

**Comment by thijstriemstra** [comment]
Ok. I wonder if something like this would work:
![20150119_213357](https://cloud.githubusercontent.com/assets/305679/5807434/974e9a4e-a023-11e4-8e16-3ae97e6b51e4.jpg)

**Comment by thijstriemstra** [comment]
`wavesurfer.drawer` is a `WaveSurfer.Drawer.Canvas` instance that creates a `wave` element. If I'm going to add a secondary `canvas` in the microphone plugin it would be useful, or necessary, to make a second `WaveSurfer.Drawer.Canvas` instance and it looks like there are several things hardcoded in there and there's currently no way to distinguish canvas1 from canvas2.

**Comment by thijstriemstra** [comment]
I managed to create something. Could you remove the 'Question:' part from the title of this ticket and reopen it @katspaugh?

**Comment by Simonn-** [comment]
@thijstriemstra have you made any progress on this?

**Comment by AbreezaSaleem** [comment]
So, I made a React package where you can record and playback your audio in real-time with the waveform graph animation! If anyone's interested, please check it out here: https://www.npmjs.com/package/react-voice-recorder-player.
