### ISSUE TITLE
new `zooming()` function breaks `zoom()` if `splitChannels=true`

### ISSUE THREAD

**Issue by marcelblum** [wavesurfer-js/wavesurfer.js#2725]
Hello, playing with the new optimized `zooming()` method from #2646 I found a bug, calling `zoom()` after having called `zooming()` fails to properly draw both channels if the parameter `splitChannels: true` is in use. Here's a demo of the problem adapted from Wavesurfer's zoom demo code:

https://codepen.io/keymapper/pen/rNZvYJa

I can look into this further when I have more time but just wanted to get it logged here, maybe @luke-harrison-personal has a better idea of where this may have broken.

**Comment by katspaugh** [comment]
Since `zooming()` is opt-in, I guess it's not urgent to fix this, but it's definitely a bug, so I'll label this issue as such.

I'm curious if perhaps in the next wavesurfer version (codename wavesurfer.ts), zooming will be performant enough as it is, so that the stretching hack won't be needed anymore?

It would be cool if you could [play around with it](https://wavesurfer-ts.pages.dev/tutorial/#/examples/zoom.js) and see if it works with your waveforms/audio files. I assume you're using the `zooming()` function because you experience a slow zoom otherwise.

Cheers!

**Comment by marcelblum** [comment]
Cool I will check that out - though on first glance https://wavesurfer-ts.pages.dev/tutorial/#/examples/zoom.js fails to fully load, getting some 404s

> I assume you're using the zooming() function because you experience a slow zoom otherwise.

Have not used `zooming()` extensively yet, just testing it out, but yeah I like the idea, anything to make rapid deep zooms smoother. It's really only a problem that comes up when using a slider as in the demo, or when using `wheel` events which can come in fast and furious especially on trackpads.

**Comment by katspaugh** [comment]
Works for me in Chrome and Safari, the only 404 I see is the missing favicon (will add that soon).

> or when using wheel events which can come in fast and furious especially on trackpads.

True!

**Comment by marcelblum** [comment]
FYI I'm getting 404s in latest Windows Chrome & Firefox for https://wavesurfer-ts.pages.dev/dist/index.js. On FF there is an error:

> Loading module from “https://wavesurfer-ts.pages.dev/dist/index.js” was blocked because of a disallowed MIME type (“”)

**Comment by katspaugh** [comment]
I’m seeing it as well after upgrading my FF. 
Thanks!

**Comment by katspaugh** [comment]
@marcelblum #2646 is now reverted in 6.6.2 because it caused another bug (see #2738).
Since zooming is much faster in the new wavesurfer.ts, I don't think we'll need to restore it.
Thanks for the report!
